### ISSUE TITLE
[Question] Actions payload in web addons

### ISSUE THREAD

**Issue by FRizzonelli** [dooboolab/dooboo-ui-native#188]
Hello guys!

First of all, you're work is amazing! I'm basically trying to understand how to set up properly storybook for RN, as I need to do build something similar to your package.
Currently, I'm stuck with actions-addon on web-server. As you already discovered, you need to downgrade the version https://github.com/storybookjs/react-native/issues/24 
I have another problem, when I tap on the device to swap story or simply opening the ondevice addon section, my actions on browser are cleared. Also the content of the synthetic event isn't correct on web-server side. Are you experiencing similar issues?

(feel free to close the issue, I'm just looking for some suggestions and information about storybook + RN are really hard to find)

Thank you so much for your time!

**Comment by JeffGuKang** [comment]
@FRizzonelli Actually I prefer to use storybook with web-server, especially when I need to control addons as knobs. So I only use navigating stories on deviceUI. 
I need to check the latest storybook version for RN what is going on. 

And I agree with you. Storybook for RN has not many information. But it hasn't been so long since it was separated to independent `storybookjs/react-native` project from the original storybook. So I am looking forward to the future of the storybook for RN.

**Comment by FRizzonelli** [comment]
@JeffGuKang Thank you for your time :) I was able to fix the problem in the syntethic event, now is working properly. Yup, while working with knobs, using web-server is much better. Last big challenge for me is to deploy a dev version directly on test iPhones, which seems to be pretty hard :(

**Comment by JeffGuKang** [comment]
@FRizzonelli I think testing on real devices is not hard to you 👍 . And I share my some scripts I am using.

```
    "ios": "react-native run-ios --simulator='iPhone 11'",
    "ios-device": "react-native run-ios --device",
    "ios-8": "react-native run-ios --simulator='iPhone 8'",
    "ipad": "react-native run-ios --simulator='iPad Air 2'",
    "android": "react-native run-android",
```
