### ISSUE TITLE
[Feature][ListItem] for lists as FlatList 

### ISSUE THREAD

**Issue by JeffGuKang** [dooboolab/dooboo-ui-native#212]
**Is your feature request related to a problem? Please describe.**
New Cell component for FlatList and others like [react-native-elements](https://react-native-elements.github.io/react-native-elements/docs/listitem.html).

**Describe the solution you'd like**
Create new feature called `Cell` or `ListItem`.

**Describe alternatives you've considered**
-

**Additional context**
- Do not use external libraries as `react-natve-vector-icons`

**Comment by hyochan** [comment]
@JeffGuKang Since we are using `expo`, it is good idea not to use `react-native-vector-icons`. How about using [@expo/vector-icons](https://docs.expo.io/guides/icons/)? We can think of `dooboo-ui` as on top of [expo](expo.io) or [expo unimodules](https://github.com/unimodules/react-native-unimodules).

**Comment by JeffGuKang** [comment]
Is it possible to use dooboo-ui without `unimodules` now? I am considering to use image for icons with customizable component if possible.

Cause https://github.com/expo/vector-icons says

> `React Native without Expo, you have no need for this library`

**Comment by hyochan** [comment]
Currently this is possible! We should avoid using vector icon then! If this is necessary we should make this into seperate package like @dooboo-ui/something
